### ISSUE TITLE
humble review

### ISSUE THREAD

**Issue by adsick** [TotalKrill/bevy_mod_reqwest#1]
I'm not a pro, bet I decided to review the code out of curiosity. It feels like it lacks some polish and may even contain bugs (I didn't tested it though)
for example [here](https://github.com/TotalKrill/bevy_mod_reqwest/blob/master/src/lib.rs#L110) you are removing `ReqwestRequest` component, but it already has been removed in the dispatch system.

It is 0:10 now, and I'm sleepy, so don't be mad if I'm yelling at your perfectly working code.

**Comment by adsick** [comment]
again, I'm not a pro, but [the docs](https://docs.rs/reqwest/latest/reqwest/struct.Client.html) suggest that you should reuse existing reqwest client, but you are copying it every time (I'm not sure if Rust allows doing it the right way, but anyway)

**Comment by adsick** [comment]
again, I'm not a pro, but [the docs](https://docs.rs/reqwest/latest/reqwest/struct.Client.html) suggest that you should reuse existing reqwest client, but you are cloning it every time (I'm not sure if Rust allows doing it the right way, but anyway)

**Comment by TotalKrill** [comment]
Hi thanks for giving this a review!

First of all, there was a bug indeed, I was removing the wrong Component in one of the systems, so thanks for spotting that, I was tired when writing this as well. 

Secondly copying the Client is actually reusing it, since it uses an Arc internally ;)

**Comment by adsick** [comment]
Oh, great, I was wrong about cloning, but now I get it)
