### ISSUE TITLE
Example using POST?

### ISSUE THREAD

**Issue by nylira** [TotalKrill/bevy_mod_reqwest#5]
Hi there! The example for GET is working for me. But it's unclear to me how to POST with this library. This is the code I'm trying to get to work:

```rust
 /* I'm trying to replicate this curl request
curl -X POST http://localhost:5000/api/generate -d '{
  "type: "purple",
  "description":"test description"
}
 */

if let Ok(url) = "http://localhost:5000/api/generate".try_into() {
    let req = reqwest::Request::new(reqwest::Method::POST, url);
    let req = ReqwestRequest::new(req);
    commands.spawn(req);
}
```

Thanks for your help!

**Comment by TotalKrill** [comment]
Thank you for using my library, I added an example in 3dc81ab, and added the json feature, so that you dont have to depend on reqwest directly with the json feature as you had to before.

**Comment by nylira** [comment]
Thanks so much!
